"""add column

Revision ID: 47f41a21b652
Revises: 
Create Date: 2024-07-10 20:45:43.096847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f41a21b652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('educations', sa.String(), nullable=True))
    op.add_column('user_details', sa.Column('children', sa.String(), nullable=True))
    op.add_column('user_details', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('user_details', sa.Column('alcohol', sa.String(), nullable=True))
    op.add_column('user_details', sa.Column('cigarettes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'cigarettes')
    op.drop_column('user_details', 'alcohol')
    op.drop_column('user_details', 'languages')
    op.drop_column('user_details', 'children')
    op.drop_column('user_details', 'educations')
    # ### end Alembic commands ###
