"""colum location try

Revision ID: c2f9e7c5a5cb
Revises: 47f41a21b652
Create Date: 2024-07-15 15:25:23.469247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f9e7c5a5cb'
down_revision = '47f41a21b652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE user_details ALTER COLUMN location TYPE JSON USING location::json')
    op.alter_column('user_details', 'location',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=False)


    # ### end Alembic commands ###


def downgrade():
    op.execute('ALTER TABLE user_details ALTER COLUMN location TYPE TEXT')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_details', 'location',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
